### ISSUE TITLE
Stuck at MarkupUI.framework/PlugIns

### ISSUE THREAD

**Issue by biocyberman** [cr/MacCaseSensitiveConversion#1]
The method presented here seems to be feasible at first, but these two directories made me quit:

```
/System/Library/PrivateFrameworks/MarkupUI.framework/PlugIns
/System/Library/PrivateFrameworks/MarkupUI.framework/Plugins
```
Diff output says they are different. And googling reveals that I should not touch anything under /System. So it's a no-go.

**Comment by cr** [comment]
> Diff output says they are different. And googling reveals that I should not touch anything under /System. So it's a no-go.

There is no reason to assume that files under */System* are any different from the rest. Once the file system is insensitive, both those references would then point to the unified directory, and I wouldn't hesitate to give it a try. Given that you keep an untouched copy of the backup around, the worst thing that can happen is that you have to revert to that one for restoring to the old state.

**Comment by biocyberman** [comment]
I went ahead to remove `/System/Library/PrivateFrameworks/MarkupUI.framework` (yes, I have a backup of it :) ). Everything went fine afterward and I got the bloody case-insensitive MacOS Sierra without re-installation :D. Big thanks to you, while I still feel irritated with Adobe CS6 that forced me to do the conversion.
