### ISSUE TITLE
Kudos!

### ISSUE THREAD

**Issue by valhovey** [cr/MacCaseSensitiveConversion#2]
Thanks so much for this guide! I was pulling my hair out after most of the applications I wanted to use refused to install on a case-sensitive file system. This would have been super arduous without your help.

**Comment by cr** [comment]
Oh, sweet! That's exactly why I wrote it all down and I am really glad it is still helpful. What version of Mac OS X did you work with, @kylehovey?

**Comment by valhovey** [comment]
High Sierra, most recent version / patch (10.13.4). Luckily I only had around 10 naming conflicts, 9 of which were in `/System`. I just deleted the first result for each of the `/System` entries and your technique worked without hassle.

**Comment by cr** [comment]
Thanks so much for your feedback! I updated the how-to according. Good to know that the technique still works on recent Macs.
